FROM openjdk:11
MAINTAINER "János Gats <gatsjanos@gmail.com>"

ENV APP_HOME=/app

RUN mkdir -p ${APP_HOME}

COPY secret/** ${APP_HOME}/secret/
COPY target/laboschcst.server.jar ${APP_HOME}/laboschcst.server.jar

WORKDIR ${APP_HOME}

EXPOSE 5005
EXPOSE 8080

CMD ["java", "-jar", "-Dspring.profiles.active=k8s_dev",  "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "laboschcst.server.jar"]
